name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: bun install --frozen-lockfile

      - run: bun run compile

      - run: bun run --filter '@sundaeswap/capacity-exchange-*' build

      - run: bun run --filter '@sundaeswap/capacity-exchange-*' --if-present test

      - name: Configure npm authentication
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.PUBLISH_NPM_TOKEN }}

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          publish: bun run publish:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
          NPM_CONFIG_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
