name: "Test"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: go-task/setup-task@v2

      # Cheap tests
      - name: Check linting/formatting
        # This check is disabled for now, I haven't run "task fix" yet
        if: ${{ false }}
        run: task check
      - name: Run tests
        run: task test

      # Expensive tests
      - name: Run testnet
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-file: ./testnet/standalone.yml
      - name: Run e2e tests
        run: task test:e2e
